language: swift
xcode_workspace: Example/WrappedValue.xcworkspace
xcode_scheme: WrappedValue-Example
xcode_destination: platform=iOS Simulator,OS=12.0,name=iPhone X
osx_image: xcode10.2
podfile: Example/Podfile
notifications:
  slack:
    secure: 0PkKBytQbs3nsv60lryI5rGIQJqchkQCpNA9q6/+JUuaArIMfKCO8gBZiIL+aZGzeFq1Ex0EA8F7Y1ocxlcJIYyLjon52LvPJV2OfR3ciODo2RNMs5pH6abQldQ1CSpZLN7rPsdSu/vJxk1fxnjN5OBOeCobsP+rbb+FySGZyEmuT48bBSDypK5se53xZjO+wHgwoEB0ZovqK0vm+ck6wfa7jeeM9RvWUJuu25fdTc7WfJI7MJhHGzU+nD/7dCmtxpazNskMiuBdyKBLKaZu98pETCfRyj4dvPyG1jhl4aQG2AsofGjdhV6BX+9tHpGAsT/dpnb88SYMw7GKOn2Iwn8tTDb62EalkodvfVwiIjzDYXMNVbeRZsWiAEH6rGE94WWo/wtUd6XrT16F8vSSORiJ8UWbPqSbqLfexW612wc4ZsAanJea/4FFc0MWa7PZifLbVS6QFq8vLJMqH4/98NpzF37OVe+IN+6MHshvmSCBjNVdR20el+qPhK0ZSMuEdfOQCeV7V3AKjRnPydilxp9aZTADZWS3Z0N99yJMGEcdQ+u0E72QipBXQ+WuSKV+l/v9fpL7kQF9FieaafD9vhWbEus4NZ1Ubglq7SXAIO1ohVzsjM6/yZZUCAHjuKizOe5oTRlqmlqKnuP9orDhnF0E5OTHjbfi5kcCtlLdivo=
    on_success: always # default: always
    on_failure: always # default: always
    on_start:   always # default: never
    on_cancel:  always # default: always
    on_error:   always # default: always