language: swift
xcode_workspace: Example/WrappedValue.xcworkspace
xcode_scheme: WrappedValue-Example
xcode_destination: platform=iOS Simulator,OS=12.0,name=iPhone X
osx_image: xcode10.2
podfile: Example/Podfile
notifications:
  slack:
    rooms: 
      - secure: "0PkKBytQbs3nsv60lryI5rGIQJqchkQCpNA9q6/+JUuaArIMfKCO8gBZiIL+aZGzeFq1Ex0EA8F7Y1ocxlcJIYyLjon52LvPJV2OfR3ciODo2RNMs5pH6abQldQ1CSpZLN7rPsdSu/vJxk1fxnjN5OBOeCobsP+rbb+FySGZyEmuT48bBSDypK5se53xZjO+wHgwoEB0ZovqK0vm+ck6wfa7jeeM9RvWUJuu25fdTc7WfJI7MJhHGzU+nD/7dCmtxpazNskMiuBdyKBLKaZu98pETCfRyj4dvPyG1jhl4aQG2AsofGjdhV6BX+9tHpGAsT/dpnb88SYMw7GKOn2Iwn8tTDb62EalkodvfVwiIjzDYXMNVbeRZsWiAEH6rGE94WWo/wtUd6XrT16F8vSSORiJ8UWbPqSbqLfexW612wc4ZsAanJea/4FFc0MWa7PZifLbVS6QFq8vLJMqH4/98NpzF37OVe+IN+6MHshvmSCBjNVdR20el+qPhK0ZSMuEdfOQCeV7V3AKjRnPydilxp9aZTADZWS3Z0N99yJMGEcdQ+u0E72QipBXQ+WuSKV+l/v9fpL7kQF9FieaafD9vhWbEus4NZ1Ubglq7SXAIO1ohVzsjM6/yZZUCAHjuKizOe5oTRlqmlqKnuP9orDhnF0E5OTHjbfi5kcCtlLdivo="
    on_success: always # default: always
    on_failure: always # default: always
    on_start:   always # default: never
    on_cancel:  always # default: always
    on_error:   always # default: always
addons:
  sonarcloud:
    organization: "cmtrounce-github" # the key of the org you chose at step #3
    token:
      - secure: "OSFywnUT0wf+pygKOP9zJWjIZLjRFQ3CG1wgQ/vm/aCH5ZXrpLIFnV32LIdDxJgh5t7kiw3e0xmBE2i0hXncI3wbwHWGEoCJbPOqsnz/eaK2izjdIcPOHyXI1p1ynqLqOHPTczP5ESCDo1B3wqlRDU3McGpJ8+vK3NK7UXVcwtUZxzW+gzDv3GrMhWt2dcD7bf55f2+plwKiY5iqyuMObZ2UT4dzwtYan4j6h2mS21/y26E1ZdMJ34p1J1R0fccoaGtEzIMEj6tCrcEOHRRx+klGKF/HdhOo3C59Lsr1DzTg331sr7DNp+SUc2ujPBiqTZZkwTbrXR7xG4vxjZaU4LS9g8qPQM9fXCGaZIkhLFIFDuNYgoeNAWLQlqPZB/yoMj6kDlnQKxoDo7LHHz15gZsbyKvywvr+OVL0gHfSk7g97bIS31I6LWklQpg2wN6E2xatBZ0jo/Ayf6j+E52d3AWy/KzDkKEwYJFdSQoWbhsrjg7NC2XvPswOClwS6I96iyTUdAX6xHa0+lRhMx/biYEtZaU10b/15dbpcXHfnOWrNRzJcB8B8Au0DfXA7wlPPo7EJuAsCZ21OIYYnepLwZlL2yTroIrJNSSJbaKlYrqDxXcrt7JLKVdbMXF8TkRRQqj+8n1rMS7bEp1GXFa8b+RD9GwNc1nL1opVRouT1pc="
script:
  # other script steps might be done before running the actual analysis
  - sonar-scanner
before_install:
  - pip install --user codecov
after_success:
  - codecov --file coverage/lcov.info --disable search